### ISSUE TITLE
Maintain file of people in official community roles

### ISSUE THREAD

**Issue by micahhausler** [tinkerbell/org#7]
The [Tinkerbell Governance document](https://github.com/tinkerbell/proposals/blob/main/proposals/0024/GOVERNANCE.md) lists four roles 

| Role        | Responsibilities | Requirements | Defined by |
| -----       | ---------------- | ------------ | ------- |
| Contributor | Submit contributions | Signed DCO | Registered GitHub User |
| Member      | Issue and discussion administration, PR reviewer | History of activity, good judgement, contribution in the community and the repositories, and sponsored by 2 Committers | Tinkerbell GitHub org member |
| Committer   | Right to make changes to the code bases, merge pull requests, etc | Same as Member, shows leadership in the community and the repositories, and sponsored by 2 Maintainers | [OWNERS] file committer entry |
| Maintainer  | Voting privileges, set direction and priorities | Same as Committer, demonstrated responsibility and excellent technical judgement for the project, and voted in by existing Maintainers | [OWNERS] file maintainer entry |

Maintainers are currently [listed in this repository](https://github.com/tinkerbell/org/blob/main/MAINTAINERS.md), but Members and Committers are not. @jacobweinstock [has an open proposal](https://github.com/tinkerbell/proposals/pull/50) for adding a section on inactivity, but it is currently manual to figure out who qualifies as inactive. 

In order to avoid the appearance of any capriciousness or unfairly singling anyone out, I propose adding a machine-readable (probably YAML) file in this repo enumerating Members, Committers, and Maintainers that a script or periodic job can run to identify (and ideally notify) current community members of any pending role changes.

This file could also function as a place where new community members can identify who qualifies as a possible sponsor for them

To start this out, it could be a simple file 
```yaml
member:
- alias: github_alias
  name: full name
- alias: other_user_alias
  name: full name
committer:
- alias: github_alias
  name: full name
- alias: other_user_alias
  name: full name
  affiliation: optional
maintainer:
- alias: thebsdbox
  name: Dan Finneran
  affiliation: Equinix Metal
- alias: tstromberg
  name: Thomas Strömberg
  affiliation: Equinix Metal
- alias: mmlb
  name: Manuel Mendez
  affiliation: Equinix Metal
```

I'm happy to take a first crack at this, but I'm not clear on who qualifies as a Committer as there aren't any filled out `OWNERS` files in any GH repos, but GH org member is easy enough to figure out.

CC @thebsdbox @tstromberg @mmlb
